### ISSUE TITLE
Missing README file / instruction to run this project

### ISSUE THREAD

**Issue by Hexagon12** [BiroStorm/TG-GroupManagerBot#2]
Hello :)
Can you write how to install your bot? 
I'd like to try your bot. I've been trying to get it started for days, but I can't.

Thanks in advance I await response :)

**Comment by BiroStorm** [comment]
Sure, I'm going to write the README.md with requirements and How to install

**Comment by Hexagon12** [comment]
> Sure, I'm going to write the README.md with requirements and How to install

Thank you! I will wait for some more news. :)

**Comment by BiroStorm** [comment]
> > Sure, I'm going to write the README.md with requirements and How to install
> 
> Thank you! I will wait for some more news. :)

I have just added the README file, I haven't used this project / bot for a long time, it should work but read the Disclamer part 😅. 
I usually run this in a docker container in production, I have just run it in console, and it works fine.
I do not advise to use this project as bot, but use it as inspiration.
You can take pieces of my code and build a new better Bot. 😄

**Comment by Hexagon12** [comment]
> > > Sure, I'm going to write the README.md with requirements and How to install
> > 
> > 
> > Thank you! I will wait for some more news. :)
> 
> I have just added the README file, I haven't used this project / bot for a long time, it should work but read the Disclamer part 😅.
> I usually run this in a docker container in production, I have just run it in console, and it works fine.
> I do not advise to use this project as bot, but use it as inspiration.
> You can take pieces of my code and build a new better Bot. 😄

What distro you use? Work on Debian?

**Comment by BiroStorm** [comment]
> > I have just added the README file, I haven't used this project / bot for a long time, it should work but read the Disclamer part 😅.
> > I usually run this in a docker container in production, I have just run it in console, and it works fine.
> > I do not advise to use this project as bot, but use it as inspiration.
> > You can take pieces of my code and build a new better Bot. 😄
> 
> What distro you use? Work on Debian?
> 
> I have forked your project.. is a problem? :)

No problem, I use windows 10 if you mean that, with Visual Studio as IDE and I use my personal Raspberry Pi 4 as server to host all of my project.
